name: R2 --> GitHub

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  S3_To_GitHub:
    runs-on: ubuntu-latest

    env:
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      WORKER_NAME: ${{ secrets.WORKER_NAME }}
      API_TOKEN: ${{ secrets.API_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Sync files to GitHub
        uses: fscarmen2/r2_to_github@v1.0.2